jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install non-GUI dependencies for unit tests
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r optional_requirements.txt
        pip install -r requirements_test.txt

    - name: Run unit tests
      run: |
        python run_unit_tests.py

  # GUI test job (only on Windows)
  gui-tests:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install GUI dependencies
      run: |
        pip install -r user_interface_requirements.txt

    - name: Run GUI tests
      run: |
        pytest tests/test_app.py -s
