name: CI for MetaDataExtractor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Unit tests on all OS
  unit-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies for unit tests
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r optional_requirements.txt
        pip install -r requirements_test.txt

    - name: Run unit tests
      run: |
        python run_unit_tests.py

  # GUI tests only on Windows
  gui-tests:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install GUI dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r user_interface_requirements.txt
        pip install git+https://github.com/pytest-dev/pytest-qt.git@master

    - name: Run GUI tests
      run: |
        pytest tests/test_app.py -s
