name: GUI Tests for Ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gui-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies for GUI tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install PyQt5==5.15.11

      - name: Install pytest-qt after PyQt5
        run: |
          pip install git+https://github.com/pytest-dev/pytest-qt.git@master

      - name: Run GUI tests
        run: |
          pytest tests/test_app.py -s
